app_login/urls.py
from .views import *
from django.conf.urls import url
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	
	url(r'^$', index, name='index'),
	url(r'^custom_auth/login/$', auth_login, name='auth_login'),
	url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
	url(r'^profile/$', profile, name='profile'),
	
]

app_mahasiswa/urls.py
from django.conf.urls import url
from .views import index_root
from .views_profile import *
from .views_riwayat import *
from .views_status import *
from .views_teman import *

urlpatterns = [
    url(r'^$', index_root, name='index'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^edit-profile/$', edit_profile_page, name='edit_profile'),
    url(r'^edit-profile/add-keahlian/(?P<id_skill>[0-9]+)/(?P<id_level>[0-9]+)/$', add_keahlian_to_database, name='add_keahlian'),
    url(r'^edit-profile/delete-keahlian/(?P<id>\w{0,50})/$', delete_keahlian, name='delete_keahlian'),
	url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id>\d+)/$', delete_status, name='delete_status'),
]

praktikum/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView

import app_mahasiswa.urls as app_mahasiswa
import app_login.urls as login


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=True), name='root'),
    url(r'^login/', include(login,namespace='app-login')),
    url(r'^mahasiswa/', include(app_mahasiswa,namespace='app-mahasiswa'))
]

app_login/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    kode_identitas = models.CharField('npm', max_length=20, primary_key=True,)
    nama = models.CharField('nama', max_length=200, default='None')
    username = models.CharField('username',max_length=200,default='None')
    profile_linkedin = models.CharField('profile_linkedin', max_length=200, default='None')
    foto_profil = models.CharField('profpic', max_length=240, default='https://heatherchristenaschmidt.files.wordpress.com/2011/09/facebook_no_profile_pic2-jpg.gif')
    email = models.CharField('email', max_length=200, default='None')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Status(models.Model):
    new_status = models.TextField(max_length=280)
    user = models.ForeignKey(User, null=True)
    created_date = models.DateTimeField(auto_now_add=True)

app_mahasiswa/models.py
from django.db import models

# Create your models here.

class Pengguna(models.Model):
    kode_identitas = models.CharField('npm', max_length=20, primary_key=True, )
    nama = models.CharField('nama', max_length=200, default = 'kosong')
    username = models.CharField('username', max_length=200, default = 'kosong')
    profile_linkedin = models.CharField('profile_linkedin', max_length=200, default = 'kosong')
    foto_profil = models.CharField('profpic', max_length = 240, default = 'http://voice4thought.org/wp-content/uploads/2016/08/default1.jpg')
    email = models.CharField('email', max_length=200, default = 'kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Status(models.Model):
    status = models.TextField()
    pengguna = models.ForeignKey(Pengguna, null = True)
    created_date = models.DateTimeField(auto_now_add=True)

class Keahlian(models.Model):
    keahlian = models.CharField('keahlian', max_length = 10)
    level = models.CharField('level', max_length = 15)
    pengguna = models.ForeignKey(Pengguna, null = True)

app_search/models.py
from django.db import models

# Create your models here.

app_mahasiswa/forms.py
from django import forms

class Status_Form(forms.Form):
	status_attrs = {
		'type': 'text',
		'rows': 4,
		'class' : 'form-control',
		'placeholder': "What's happening?",
		'style': 'resize:none'
	}
	
	status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

app_login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import User
from django.urls import reverse
# Create your views here.

response = {}

def index(request):# pragma: no cover
    if 'user_login' in request.session:
        response['login'] = True
        return HttpResponseRedirect(reverse('app-mahasiswa:profile'))

    else :
        response['login'] = False
        html = 'app_login/session/login.html'
        return render(request, html, response)


def profile(request):# pragma: no cover
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('app-login:index'))
    else:
        kode_identitas = request.session['kode_identitas']
        try:
            user = User.objects.get(kode_identitas = kode_identitas)
            set_data_for_session(user)
        except Exception as e:
            user = User()
            user.kode_identitas = kode_identitas
            user.username = request.session['user_login']
            user.save()
            set_data_for_session(user)

        html = 'app_login/session/profile.html'
        return render(request, html, response)

def set_data_for_session(user):# pragma: no cover
    response['author'] = user.username
    response['npm'] = user.kode_identitas
    response['foto_profil'] = user.foto_profil
    response['nama'] = user.nama
    response['profile_linkedin'] = user.profile_linkedin
    response['email'] = user.email

app_mahasiswa/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
# Create your views here.

response = {'author' : "x, x, x, x"}

def index_root(request):# pragma: no cover
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect('/login/')

    return HttpResponseRedirect('/mahasiswa/profile')

app_search/views.py
from django.shortcuts import render

# Create your views here.

app_login/templates/app_login/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="author" content="{{author}}">

  <title>
    {% block title %} Login Page {% endblock %}
  </title>
</head>
<body>
  <content>
    {% block content %}
    <!-- Your Content Here -->
    {% endblock %}
  </content>
</body>
</html>

app_login/templates/app_login/session/login.html
{% extends "app_login/layout/base.html" %}
{% block content %}
<style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #42e2f4;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}
#id00 {
    min-width: 300px;
    height: 155px;
    top: 50%;
}
.wrapper {
    text-align: center;
}
#word{
    font-family: comic sans ms;
    color: blue;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
    font-family: verdana
}


.container {
    padding: 16px;
    font-family: verdana
}

span.password {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;

    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 50%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 720px) {
    span.password {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
    #b123{
        width: 50%;
    }
}
</style>
    <div class="wrapper">
        <div><button id="id00" onclick="document.getElementById('id01').style.display='block'" style="width:auto;"><img id="b123" src="https://erslibrary.tcoe.org/images/default-source/TeenPortal/loginbutton.png?sfvrsn=0"></button>
        </div>
        <div class="wrapper">
            <h1 id="word">welcome to BUKAmata</h1>
        </div>
    </div>

<div id="id01" class="modal">

  <form class="modal-content animate" action="{% url 'app-login:auth_login' %}" method="POST">
    {% csrf_token %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <p> Silahkan Login menggunakan <strong> AKUN SSO </strong>
    </div>

    <div class="container">
      <label><b>Username</b></label>
      <input type="text" id="username" name="username" required>

      <label><b>Password</b></label>
      <input type="password" id="password" name="password" required>

      <button type="submit">Login</button>
    </div>
  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>
{% endblock %}

app_mahasiswa/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 9">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- css kelompok -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="../../static/tugas_2.css" >
    <title>
        {% block title %} Tugas 2 {{author}} {% endblock %}
    </title>
</head>
<body>
<header>
    <!-- Your Header Here -->
    {% include "partials/header.html" %}
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    {% block footer %}
    <!-- Your Footer Here -->
    {% include "partials/footer.html" %}
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- script tugas -->
<script src="{% static 'js/profile.js' %}"></script>
<script src="{% static 'js/riwayat.js' %}"></script>
<script src="{% static 'js/status.js' %}"></script>
<script src="{% static 'js/teman.js' %}"></script>
</body>
</html>

app_mahasiswa/templates/partials/footer.html
<div class="footer">
	<p><br>© 2017 Coded with love by Us. All rights reserved</p>
</div>

app_mahasiswa/templates/partials/header.html
<!-- templates/lab_5/partials/header.html -->

app_mahasiswa/templates/session/edit_profile.html
{% extends "layout/base.html" %}
{% block content %}

<div class = "container">
    <div class = "header-html" align = "center">
        <br>
        <img src = "{{ foto_profil }}" alt = "profpic" width = "200px" height = "200px">
        <p>{{ npm }}</p>
    </div>
    <div class = "edit-content-html">
        <p>Data Pribadi</p>
        <div class = "linked-in-data-content">
            <!-- notyet -->
        </div>
        <div class = "keahlian-content" style = "width:90%;">
            {% if list_keahlian %}
                {% for keahlian in list_keahlian %}
                    <div class = "some-word">{{ forloop.counter }} &nbsp;&nbsp;&nbsp;&nbsp;
                    <select class = "select-keahlian" data-id = "{{ keahlian.id }}" >
                            <option value="{{keahlian.keahlian}}">{{keahlian.keahlian}}</option>
                            <option value="0">Java</option>
                            <option value="1">C#</option>
                            <option value="2" >Python</option>
                            <option value="3">Erlang</option>
                            <option value="4">Kotlin</option>
                        </select>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <select class = "select-level" data-id = "{{ keahlian.id }}">
                            <option value="{{keahlian.level}}">{{keahlian.level}}</option>
                            <option value="0">Beginner</option>
                            <option value="1">Intermediate</option>
                            <option value="2">Advanced</option>
                            <option value="3">Expert</option>
                            <option value="4">Legend</option>
                        </select>
                        <button class = "btn btn-danger delete-button"  data-id = "{{ keahlian.id }}">Delete Keahlian</button>
                    </div>
                    <br>
                {% endfor %}
            {% endif %}
            <div class = "keahlian-baru" >
                {{ list_keahlian | length | add:1}} &nbsp;&nbsp;&nbsp;&nbsp;
                <select class = "select-keahlian skill-baru" data-id = "{{ forloop.counter }}">
                    <option value="0" selected>Java</option>
                    <option value="1">C#</option>
                    <option value="2" >Python</option>
                    <option value="3">Erlang</option>
                    <option value="4">Kotlin</option>
                </select>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <select class = "select-level level-baru">
                    <option value="0" selected>Beginner</option>
                    <option value="1">Intermediate</option>
                    <option value="2" >Advanced</option>
                    <option value="3">Expert</option>
                    <option value="4">Legend</option></select>
                <button class = "btn btn-primary apply-button" onClick="addKeahlian()">Tambah Keahlian</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app_mahasiswa/templates/session/mahasiswaPage.html
{% extends "layout/base.html" %}
{% load static %}
{% block content %}
<!-- Content Here -->
<!-- tulisan nama, status terakhir, dll di sini-->

<h1>Selamat Datang, {{ username }}</h1>
<img src = "{{ foto_profil }}" alt = "profpic" width = "200px" height = "200px">
<a href = "" class = "btn btn-primary">Lihat Forum</a> 
<a href = "{% url 'app-mahasiswa:edit_profile' %}" class = "btn btn-primary">Edit Profile</a> 
<h3>Jumlah Status : {{ total }} </h3>
<h3>
    <!-- if ada status, get status terakhir pake filter(-date) < cek status di tugas1
        kalo ga ada tinggal taro tidak ada status
     -->
</h3>


<!-- logout sementara -->
<a href="{% url 'app-login:auth_logout' %}" class="btn btn-danger pull-right" onclick="return confirm('Keluar?')">Logout </a>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#profile" aria-controls="home" role="tab" data-toggle="tab"> Profile </a>
        </li>
        <li role="presentation">
            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
        </li>
        <li role="presentation">
            <a href="#status" aria-controls="settings" role="tab" data-toggle="tab"> Status </a>
        </li>
        <li role="presentation">
            <a href="#teman" aria-controls="settings" role="tab" data-toggle="tab"> Teman </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="profile">
            {% include 'tables/profile.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="riwayat">
            {% include 'tables/riwayat.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="status">
            {% include 'tables/status.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="teman">
            {% include 'tables/teman.html' %}
        </div>
    </div>
</div>
{% endblock %}

app_mahasiswa/templates/tables/profile.html
{% load staticfiles %}
{% load static %}

<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-lg-6 col-lg-12">
            <table width="80%">
                <tr>
                    <td><h5><strong>Nama</strong></h5></td>
                    <td><h5> : {{ username }}</h5></td>
                </tr>
                <tr>
                    <td><h5><strong>NPM</strong></h5>
                    <td><h5> : {{ npm }}</h5></td>
                </tr>
                <tr>
                    <td><h5><strong>Keahlian</strong></h5></td>
                    <td> :
                        <div class="keahlian">
                            {% if list_keahlian %}
                                {% for keahlian in list_keahlian %}
                                    {% if keahlian.keahlian == 'Java' %}
                                        <button class="btn btn btn-primary">{{ keahlian.keahlian }}</button> 
                                    {% elif keahlian.keahlian == 'Python'%}
                                        <button class="btn btn btn-danger">{{ keahlian.keahlian }}</button> 
                                    {% else%}
                                        <button class="btn btn btn-success">{{ keahlian.keahlian }}</button> 
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                kosong
                            {% endif %}
                        </div> 
                    </td>
                </tr>
                <tr>
                    <td><h5><strong>Email</strong></h5></td>
                    <td><h5> : {{ email }}</h5></td>
                </tr>
                <tr>
                    <td><h5><strong>Profile LinkedIn</strong></h5></td>
                    <td><h5> : {{ profile_linkedin }}</h5></td>
                </tr>
            </table>
        </div>
    </div>
</div>

app_mahasiswa/templates/tables/riwayat.html
{% load staticfiles %}
{% load static %}

<div class="panel panel-default">
	<div class="panel-heading">
		<table style="width: 97%;">
	     	<thead>
		       <tr>
		         <th class="col-xs-2">No</th>
		         <th class="col-xs-4">Mata Kuliah</th>
		         <th class="col-xs-4">Dosen Pengajar</th>
		         <th id="nilai" class="col-xs-2">Nilai</th>
		       </tr>
		     </thead>
		</table>
   	</div>
    <div class="panel-body">
        <table class="table table-fixed">
	     <tbody>
	     	{% for matkul in list_matkul %}
		       <tr>
		         <td class="col-xs-2">{{ forloop.counter }}</td>
		         <td class="col-xs-4">{{ matkul.kelas.nm_mk_cl.nm_mk }}</td>
		         <td class="col-xs-4">{{ matkul.kelas.pengajar.0.nama }}</td>
		         <td id="nilai" class="col-xs-2">{{ matkul.nilai }}</td>
		       </tr>
		     {% endfor %}
	     </tbody>
	   </table>
    </div>
</div>

app_mahasiswa/templates/tables/status.html
{% load staticfiles %}
<div class="panel panel-info">
        <div class="panel-body">
            <section name="input-list" id="input-list">
                <div class="container" style="width:100%;">
                	<form id="form" method="POST" action="{% url 'app-mahasiswa:add_status' %}">
                        <h2>Update Status</h2>
                        {% csrf_token %}
                        {{ status_form }}
                        <br>
                        <input id="post-button" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
                    </form>
                </div>
            </section>
            <section name="my-list" id="my-list">
                <div class="container" style="width:100%;">
                    <h2 class="my-list-title">Timeline</h2>
                    <div class="flex">
                    {% if status %}
                    	{% for data in status %}
                            <div class="flex-item status-flex">
                                <a href="/mahasiswa/delete_status/{{ data.id }}">
                                    <div class="delete-button" data-id={{data.id}}}>x</div>
                                </a>
                                <div class="postee">
                                    <img class="img depe" src = "https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png" width="50px">
                                    {{ data.pengguna.username }}
                                </div>
            				    <div class="isi-status">{{data.status}}</div>
            				    <div class="date-added" id="date-added">{{data.created_date}}</div>
                            </div>
                    	{% endfor %}
                    {% else %}
                    <div class="alert alert-danger text-center">
                        <strong>Oops!</strong> Tidak ada post di timeline.
                    </div>
                    {% endif %}
                  </div>
                </div>
            </section>
        </div>
    </div>
{% load static %}

app_mahasiswa/templates/tables/teman.html
{% load staticfiles %}
{% load static %}
{% block content %}

{% endblock %}